#!/bin/bash
# bootstrap script

if [[ ${#} -lt 2 ]]; then
	echo "Insufficient parameters provided."
else
	digikube_repo="${1}"
	bootstrap_command="${2}"
	
	if [[ "${bootstrap_command}" == "create" ]]; then
		#wget -q --no-cache -O - "${digikube_repo}/cloud-init/gce-cloud-init.sh" | bash
		echo "wget -q --no-cache -O - ${digikube_repo}/cloud-init/gce-cloud-init.sh | bash"
	else
		read -p "Enter delete scope:\n
					Only K8S Cluster: cluster\n
					K8S Cluster with bastion host:	bastion-host\n
					K8S Cluster, bastion-host, cloud-resourses: all\n
					K8S Cluster, bastion-host, cloud-resources, bucket:	all-with-bucket\n
					>> : " delete_scope	
		#wget -q --no-cache -O - "${digikube_repo}/cloud-init/gce-cloud-delete.sh ${delete_scope}" | bash
		echo "wget -q --no-cache -O - ${digikube_repo}/cloud-init/gce-cloud-delete.sh ${delete_scope} | bash"
	fi
fi
