#!/bin/bash
# bootstrap script

if [[ $# -lt 2 ]]; then
	echo "Insufficient parameters provided."
else
	digikube_repo="$1"
	bootstrap_command="$2"
	
	if [[ "${bootstrap_command}" == "create" ]]; then
		echo "wget -q --no-cache -O - ${digikube_repo}/cloud-init/gce-cloud-init.sh | bash"
		wget -q --no-cache -O - "${digikube_repo}/cloud-init/gce-cloud-init.sh" | bash
	else
		echo "Please enter delete scope:"
		echo "            Only K8S Cluster                                   : cluster"
		echo "            K8S Cluster with bastion host                      : bastion-host"
		echo "            K8S Cluster, bastion-host, cloud-resourses         : all"
		echo "            K8S Cluster, bastion-host, cloud-resources, bucket : all-with-bucket"
		read -p "Enter your choice: " delete_choice
		export delete_choice=${delete_choice}
		echo "wget -q --no-cache -O - ${digikube_repo}/cloud-init/gce-cloud-delete.sh | bash"
		wget -q --no-cache -O - "${digikube_repo}/cloud-init/gce-cloud-delete.sh" | bash
	fi
fi
