#!/bin/bash
# Init script

DIGIKUBE_BASE_DIR="/etc/digikube"
DIGIKUBE_EXEC_DIR="/etc/digikube/exec"
DIGIKUBE_CORE_DIR="/etc/digikube/core"
DIGIKUBE_CLUSTERS_DIR="/etc/digikube/clusters"

digikubeCloudAdminUser=""		# Will be set dynamically in bellow line
digikubeCodeRawRepoUrl=""		# Will be set dynamically in bellow line
digikubeInstanceRawRepoUrl=""		# Will be set dynamically in bellow line

#Do not change the bellow line -- will be replaced at runtime
#<placeholder for digikube admin user name>
#<placeholder for digikube code raw repo url>
#<placeholder for digikube instance raw repo url>

tmpExecDir=$(mktemp -d --suffix="-digikube")
chown "${digikubeCloudAdminUser}":"${digikubeCloudAdminUser}" "${tmpExecDir}"
echo "DEBUG: Temporary execution directory is ${tmpExecDir}"

initShellLog="${tmpExecDir}/init-shell.log"
su - "${digikubeCloudAdminUser}" --preserve-environment -c "touch ${initShellLog}"

echo "INFO: Started init-shell." >> "${initShellLog}"
echo "DEBUG: Executing steps with identity of ${digikubeCloudAdminUser}" >> "${initShellLog}"
echo "DEBUG: Digikube code raw repo url is ${digikubeCodeRawRepoUrl}" >> "${initShellLog}"
echo "DEBUG: Digikube instance raw repo url is ${digikubeInstanceRawRepoUrl}" >> "${initShellLog}"

if [[ -d ${DIGIKUBE_BASE_DIR} ]]; then
	echo "DEBUG: Digikube base directory (${DIGIKUBE_BASE_DIR}) already available" >> "${initShellLog}"
else
	mkdir "${DIGIKUBE_BASE_DIR}"
	chown "${digikubeCloudAdminUser}":"${digikubeCloudAdminUser}" "${DIGIKUBE_BASE_DIR}"
	echo "DEBUG: Digikube base directory (${DIGIKUBE_BASE_DIR}) created" >> "${initShellLog}"
fi

echo "INFO: Attempting to download init script" >> "${initShellLog}"
initScriptSource="wget -q --no-cache -O ${tmpExecDir}/gce-bastion-host-init - ${digikubeCodeRawRepoUrl}/cloud-init/gce-bastion-host-init"
echo "DEBUG: Init script source is ${initScriptSource}" >> "${initShellLog}"

su - "${digikubeCloudAdminUser}" --preserve-environment -c "${initScriptSource}"
__returnCode=${?}
__returnCode=0    # Wget is returning exit code 4 even after success.  
if [[ ${__returnCode} -gt 0 ]]; then
	echo "ERROR: Error while downloading the init script ${initScriptSource}.  Error code is ${__returnCode}" >> "${initShellLog}"
	exit ${__returnCode}
else
	echo "INFO: Download init script" >> "${initShellLog}"
fi

echo "INFO: Attempting change the permissions on the init script" >> "${initShellLog}"
su - "${digikubeCloudAdminUser}" --preserve-environment -c "chmod +x ${tmpExecDir}/gce-bastion-host-init"
__returnCode=${?}
if [[ ${__returnCode} -gt 0 ]]; then
	echo "ERROR: Error while changing the permissions of init script.  Error code is ${__returnCode}" >> "${initShellLog}"
	exit ${__returnCode}
else
	echo "INFO: Changed permissions of init script" >> "${initShellLog}"
fi

echo "INFO: Attempting to execute init script" >> "${initShellLog}"
su - "${digikubeCloudAdminUser}" --preserve-environment -c "${tmpExecDir}/gce-bastion-host-init ${digikubeCodeRawRepoUrl} ${digikubeInstanceRawRepoUrl}"
__returnCode=${?}
if [[ ${__returnCode} -gt 0 ]]; then
	echo "ERROR: Error while executing init script.  Error code is ${__returnCode}" >> "${initShellLog}"
	exit ${__returnCode}
else
	echo "INFO: Executed init script" >> "${initShellLog}"
fi

echo "INFO: Attempting to delete temporary execution directory" >> "${initShellLog}"
rm -rf "${tmpExecDir}"
__returnCode=${?}
if [[ ${__returnCode} -gt 0 ]]; then
	echo "ERROR: Error while deleting temporary execution directory.  Error code is ${__returnCode}" >> "${initShellLog}"
	exit ${__returnCode}
else
	echo "INFO: Executed init script"
fi

#su - "${digikubeCloudAdminUser}" --preserve-environment -c "touch ${digikube_init_lock}"
