#!/bin/sh
# Init script
# Input parameters
#	$1 => digikube code repository url
#	$2 => digikube instance repository url

providedDigikubeCodeRawRepoUrl=${1}
providedDigikubeInstanceRawRepoUrl=${2}

DIGIKUBE_BASE_DIR="/etc/digikube"
DIGIKUBE_EXEC_DIR="/etc/digikube/exec"
DIGIKUBE_CORE_DIR="/etc/digikube/core"
DIGIKUBE_CLUSTERS_DIR="/etc/digikube/clusters"

mkdir -p ${DIGIKUBE_BASE_DIR}/{exec/log,core/lock,clusters}

tmpExecDir=$(mktemp -d --suffix="-digikube")
echo "DEBUG: Temporary execution directory is ${tmpExecDir}"

initLog="${tmpExecDir}/init.log"
touch "${initLog}"

echo "INFO: Started init script" >> "${initLog}"
echo "DEBUG: Digikube code raw repo url is ${providedDigikubeCodeRawRepoUrl}" >> "${initLog}"
echo "DEBUG: Digikube instance raw repo url is ${providedDigikubeInstanceRawRepoUrl}" >> "${initLog}"

providedDigikubeCodeRawRepoUrl=https://raw.githubusercontent.com/samdesh-gcp1/digikube/master
providedDigikubeCodeGitRepoUrl="${providedDigikubeCodeRawRepoUrl/raw\.githubusercontent\.com/github\.com}"
providedDigikubeCodeGitRepoUrl="${providedDigikubeCodeGitRepoUrl/\/master/\.git}"

https://github.com/samdesh-gcp1/digikube.git


GIT_REPO_URL="https://github.com/samdesh-gcp1/digikube.git"
DIGI_DIR=${BASE_DIR}digikube/
MAIN_INSTALLER=${DIGI_DIR}installer/main-installer

if [[ -d ${DIGI_DIR} ]]; then
	echo "Dikiguke source directory exists. Refreshing." >> ${INIT_LOG}
	cd ${DIGI_DIR}
	git init
	if [ $? -gt 0 ]; then
		echo "Error while refreshing dikiguke source directory. Aborting." >> ${INIT_LOG}
		exit 1
	else
		echo "Refreshed dikiguke source directory." >> ${INIT_LOG}
		cd ${DIGI_DIR}
		git pull
		if [ $? -gt 0 ]; then
			echo "Error while pulling dikiguke source directory. Aborting." >> ${INIT_LOG}
			exit 1
		else
			echo "Pulled dikiguke source directory." >> ${INIT_LOG}
		fi	
	fi	
else
	echo "Digikube source directory not available. Clonning" >> ${INIT_LOG}
	cd ${BASE_DIR}
	git clone -o digikube-source ${GIT_REPO_URL}
	if [ $? -gt 0 ]; then
		echo "Error while clonning dikiguke source directory. Aborting." >> ${INIT_LOG}
		exit 1
	else
		echo "Clonned dikiguke source directory." >> ${INIT_LOG}
	fi	
fi

if [[ -e ${MAIN_INSTALLER} ]]; then
	echo "Starting digikube main installation." >> ${INIT_LOG}
	${MAIN_INSTALLER}
	if [[ $? -gt 0 ]]; then
		echo "Error during Digikube installation.  Please check installation log for details." >> ${INIT_LOG}
		exit 1
	else
		echo "Completed Digikube installation.  Please check installation log for details." >> ${INIT_LOG}
	fi
else
	echo "Digikube main installer not found. Aborting." >> ${INIT_LOG}
	exit 1
fi

