#!/bin/bash
# bootstrap preparation script

repo_url=$1

var1='{"check_jq":"check_jq"}'
var2=$(echo $var1 | jq '.check_jq')
__returnCode=$?
if [[ __returnCode -gt 0 ]]; then
	echo "jq command not available.  Installing..."
	sudo apt-get install jq
else
	echo "jq command already installed."
fi

yaml2json_file_url="$repo_url/bin/yaml2json"
yaml2json_file="/usr/local/bin/yaml2json"
if [[ -f ${yaml2json_file} ]]; then
	echo "yaml2json command already installed."
else
	echo "yaml2json command not available.  Installing..."
	sudo wget -q --no-cache -O "$yaml2json_file" - "$yaml2json_file_url" 
	sudo chmod +x "$yaml2json_file"
fi
