#!/bin/bash
#Controller for apps

__function_name="cluster/app-controller"

base_dir=~/
digi_dir=${base_dir}digikube/

. ${digi_dir}utility/general.sh
. ${digi_dir}utility/log.sh
. ${digi_dir}common/digikube-config.sh

__app_type="${1}"
__app_name="${2}"
__app_command="${3}"
__app_command_param="${4}"

is_app_enabled=$(get-config-value "cluster.${__app_type}.${__app_name}.enabled")
if [[ -z ${is_app_enabled} ]]; then
	#The configuration is not defined for this application
	echo "Application is not defined in configuration"
	exit 1
else
	if [[ "${is_app_enabled}" == "true" ]]; then
		#The app configuration is enabled
		echo "Application is enabled in configuration"
		is_command_enabled=$(get-config-value "cluster.${__app_type}.${__app_name}.omCommands.${__app_command}")
		if [[ -z ${is_command_enabled} ]]; then
			#Command is not defined
			echo "Command is not defined in configuration"
			exit 1
		else
			if [[ "${is_command_enabled}" == "true" ]]; then
				#Command is enabled in configuration"
				echo "Command is enabled in configuration"
				__deployment_engine=$(get-config-value "cluster.${__app_type}.${__app_name}.deploymentEngine")
				case ${__deployment_engine} in 
					"cmd")	
						__app_om_shell="${digi_dir}cluster/om/${__app_name}-om"
						${__app_om_shell} ${__app_command} "${__app_command_param}"
						__return_code=$?
						;;
					"helm-chart")
						__app_om_shell="${digi_dir}cluster/apps-om/helm-chart-om"
						${__app_om_shell} ${__app_name} ${__app_command} "${__app_command_param}"
						__return_code=$?
						;;
					"kubectl-apply")
						__app_om_shell="${digi_dir}cluster/om/kubectl-apply-om"
						__deployment_params=$(get-config-value "cluster.${__app_type}.${__app_name}.deploymentParams")
						${__app_om_shell} ${__app_name} ${__app_command} ${__deployment_params} "${__app_command_param}"
						__return_code=$?
						;;
					"kubectl-crew")
						#Need to change this section
						__app_om_shell="${digi_dir}cluster/om/kubectl-crew-om"
						__deployment_params=$(get-config-value "cluster.${__app_type}.${__app_name}.deploymentParams")
						${__app_om_shell} ${__app_name} ${__app_command} ${__deployment_params} "${__app_command_param}"
						__return_code=$?
						;;
					*)
						echo "Unknown deployment engine specified in config: ${__deployment_engine}"
						exit 1
				esac

				if [[ ${__return_code} -gt 0 ]]; then
					#Error while executing the command
					echo "Error while executing the command"
					exit 1
				else
					#Command executed successfully
					echo "Command executed successfuly"
				fi
			else
				#Command is disabled in configuration
				echo "Command is disabled in configuration"
				exit 1
			fi
		fi
	else
		echo "Application is disabled in configuration"
		exit 1
	fi
fi
