#!/bin/bash
# main digiops shell

__function_name="cluster/digiops"

base_dir=~/
digi_dir=${base_dir}digikube/

cluster_controller=${digi_dir}cluster/cluster-controller
sys_app_controller=${digi_dir}cluster/sys-apps-controller
sample_app_controller=${digi_dir}cluster/sample-apps-controller

if [[ $# -gt 0 ]]; then
	scope_name="${1}"
	if [[ "${scope_name}" == "cluster" ]]; then
		command_name="${2}"
		command_param="${3}"
		${cluster_controller} ${command_name} ${command_param}
	else
		if [[ "${scope_name}" == "sys-apps" || "${scope_name}" == "platform-apps" || "${scope_name}" == "sample-apps" ]]; then
			app_type="${1}"
			app_name="${2}"
			command_name="${3}"
			command_param="${4}"
			${sys_app_controller} ${app_type} ${app_name} ${command_name} ${command_param} 
		else
			echo "Unknown scope ${scope_name}"
			exit 1
		fi
	fi
fi
