#!/bin/bash

base_dir=~/
digi_dir=${base_dir}digikube/

. ${digi_dir}utility/general.sh
. ${digi_dir}utility/log.sh
. ${digi_dir}common/digikube-config.sh


function get-cluster-config {
    
    #Function to get the digikube configuration details.
    __function_name="cluster/digiops.get-cluster-config"

    #This environment variable is required.
    export KOPS_FEATURE_FLAGS=$(get-config-value "cluster.kops.featureFlags")
    export KOPS_STATE_STORE="gs://$(get-config-value 'cloud.bucket.name')"
    
    kops_feature_flags=${KOPS_FEATURE_FLAGS}
    kops_state_store=${KOPS_STATE_STORE}
    kops_cloud=$(get-config-value "cloud.provider")
