#!/bin/bash
#OM for helm chart based system apps

base_dir=~/
digi_dir=${base_dir}digikube/

. ${digi_dir}utility/general.sh
. ${digi_dir}utility/log.sh
. ${digi_dir}common/digikube-config.sh
   
digikube_config=${digi_dir}config/digikube-config.yaml
parse_yaml ${digikube_config} "__config_"

function create {

	__function_name="cluster/apps-om/helm-chart-om.create"
	
	app_type="${1}"
	app_name="${2}"
	app_command_param="${3}"

	chart_repo_url=$(get-config-value "cluster.${app_type}.${app_name}.deploymentEngine.chartRepoUrl")
	chart_repo=$(get-config-value "cluster.${app_type}.${app_name}.deploymentEngine.chartRepo")
	chart_name=$(get-config-value "cluster.${app_type}.${app_name}.deploymentEngine.chartName")
	release_name=$(get-config-value "cluster.${app_type}.${app_name}.deploymentEngine.releaseName")
	chart_values=$(get-config-value "cluster.${app_type}.${app_name}.deploymentEngine.chartValues")
	chart_values_file=${digi_dir}cluster/${app_type}/${app_name}/config/${chart_values}
	release_namespace=$(get-config-value "cluster.${app_type}.${app_name}.deploymentEngine.namespace")
	
	pre_execution_hook_shell=${digi_dir}cluster/${app_type}/${app_name}/bin/pre-execution-hook
	if [[ -f ${pre_execution_hook_shell} ]]; then
		${pre_execution_hook_shell}
		if [[ ${?} -gt 0 ]]; then
			echo "error"
			exit 1
		fi
	fi
	
	kubectl get namespace ${release_namespace}
	if [[ ${?} -gt 0 ]]; then
		echo "Namespace not available: ${release_namespace}.  Creating new"
		kubectl create namespace ${release_namespace}
		if [[ ${?} -gt 0 ]]; then
			echo "Error while creating namespace: ${release_namespace}.  Aborting."
			exit 1
		else
			echo "Created namespace: ${release_namespace}"
		fi
	fi
	
	__deployment=$(kubectl get deployment -l release=${release_name} --namespace ${release_namespace} |  sed -n 2p | awk '{print $1;}')
	#kubectl get deployment -l release=${release_name} --namespace ${release_namespace}
	if [[ -z ${__deployment} ]]; then
		echo "helm install ${release_name} ${chart_repo}/${chart_name} --namespace ${release_namespace} -f ${chart_values_file}"
		helm repo add ${chart_repo}/${chart_name} ${chart_repo_url}
		helm repo update
		helm install ${release_name} ${chart_repo}/${chart_name} --namespace ${release_namespace} -f ${chart_values_file}
		echo "Installation done... executing post installation hooks"
		post_execution_hook_shell=${digi_dir}cluster/${app_type}/${app_name}/bin/post-execution-hook
		if [[ -f ${post_execution_hook_shell} ]]; then
			${post_execution_hook_shell}
			if [[ ${?} -gt 0 ]]; then
				echo "error"
				exit 1
			fi
		fi
	else
		echo "Release already available with name: ${release_name}.  Please delete it or use update command."
		exit 1
	fi
}

function delete {

	__function_name="cluster/apps-om/helm-chart-om.delete"
	
	app_type="${1}"
	app_name="${2}"
	app_command_param="${3}"

	release_name=$(get-config-value "cluster.${app_type}.${app_name}.deploymentEngine.releaseName")
	release_namespace=$(get-config-value "cluster.${app_type}.${app_name}.deploymentEngine.namespace")
	
	kubectl get namespace ${release_namespace}
	if [[ ${?} -gt 0 ]]; then
		echo "Namespace not available: ${release_namespace}.  Aborting"
		exit 1
	fi
	
	__deployment=$(kubectl get deployment -l release=${release_name} --namespace ${release_namespace} |  sed -n 2p | awk '{print $1;}')
	#kubectl get deployment -l release=${release_name} --namespace ${release_namespace}
	if [[ -z ${__deployment} ]]; then
		echo "No release available with name: ${release_name}. Aborting."
		exit 1
	else
		echo "helm delete ${release_name} --namespace ${release_namespace}"
		helm delete ${release_name} --namespace ${release_namespace}
	fi
}

function get_release {

	__function_name="cluster/apps-om/helm-chart-om.get_release"
	
	app_type="${1}"
	app_name="${2}"
	app_command_param="${3}"

	release_name=$(get-config-value "cluster.${app_type}.${app_name}.deploymentEngine.releaseName")
	release_namespace=$(get-config-value "cluster.${app_type}.${app_name}.deploymentEngine.namespace")
	
	echo "kubectl get deployment -l release=${release_name} --namespace ${release_namespace} |  sed -n 2p | awk '{print $1;}'"
	__deployment=$(kubectl get deployment -l release=${release_name} --namespace ${release_namespace} |  sed -n 2p | awk '{print $1;}')
	#kubectl get deployment -l release=${release_name} --namespace ${release_namespace}
	if [[ -z ${__deployment} ]]; then
		echo "No release available with name: ${release_name}."
		exit 1
	else
		echo "Release available with name: ${release_name} in namespace: ${release_namespace}."
	fi
}

app_type="${1}"
app_name="${2}"
app_command_option=${3}
app_command_param="${4}"

#This will load additional command options (like validate, downgrade, clean, purge, deep-delete, etc.)
echo "helm_chart_om_extension_shell=${digi_dir}cluster/${app_type}/${app_name}/bin/helm-chart-om-extension"
helm_chart_om_extension_shell=${digi_dir}cluster/${app_type}/${app_name}/bin/helm-chart-om-extension
if [[ -f ${helm_chart_om_extension_shell} ]]; then
	echo "Extension shell available"	
	${helm_chart_om_extension_shell} 
	if [[ ${?} -gt 0 ]]; then
		echo "error"
		exit 1
	fi
else
	echo "Extension shell not available"
fi

case ${app_command_option} in 
	"create")	
		create "${app_type}" "${app_name}" "${app_command_param}"
		;;
	"delete")
		delete "${app_type}" "${app_name}" "${app_command_param}"
		;;
	"update")
		update "${app_type}" "${app_name}" "${app_command_param}"
		;;
	"getRelease")
		get_release "${app_type}" "${app_name}" "${app_command_param}"
		;;
	*)
		#echo "Command not known: ${shell_command_option}"
		${app_command_option}
		if [[ $? -eq 0 ]]; then
			${app_command_option} "${app_type}" "${app_name}" "${app_command_param}"
		else
			echo "Command not available ${app_command_option}"
			exit 1
		fi
esac
