# Base configuration for the Digikube
cloud:
  provider: "gce"
  adminUser: "samdesh_gcp1"
  project:
    id: "digikube003"
    region: "us-central1"
    zone: "us-central1-c"
  bucket:
    class: "STANDARD"
  bastionHost:
    name: "bastion-host-1"
    machineType: "f1-micro"
    networkTier: "STANDARD"
    preemptible: "yes"
    tagIdentifier: "bastion-host"
    tags: "http-server,https-server"
    image: "ubuntu-1804-bionic-v20191211"
    imageProject: "ubuntu-os-cloud"
    bootDiskSize: "10GB"
    bootDiskType: "pd-standard"
gitConfig:
  digikubeCode:
    cloneRepoUrl: "https://github.com/samdesh-gcp1/digikube.git"
    rawRepoUrl: "https://raw.githubusercontent.com/samdesh-gcp1/digikube/master"
cluster:
  identity:
    env: "dev1"
    namePrefix: "c1" 
    domain: "k8s.local"
  master:
    countMin: 1
    countMax: 1
    zone: "us-central1-c"
    size: "g1-small"
    volumeSize: 10
    image: "cos-cloud/cos-stable-65-10323-99-0"
  node:
    countMin: 2
    countMax: 2
    zone: "us-central1-c"
    size: "g1-small"
    volumeSize: 10
    image: "cos-cloud/cos-stable-65-10323-99-0"
  kopsFlags:
    featureFlags: "AlphaAllowGCE"
    associatePublicIp: "false"  
    preemptible: "true"
