#!/bin/bash
# digiops installer

__function_name="installer/digiops-installer"

base_dir=~/
digi_dir=${base_dir}digikube/

. ${digi_dir}utility/general.sh
. ${digi_dir}utility/log.sh

digikube_config=${digi_dir}config/digikube-config.yaml
parse_yaml ${digikube_config} "__config_"

log_it "${__function_name}" "installer" "INFO" "1210" "Started the digiops installation process"

digiops_download_version=${__config_component_digiops_version}
log_it "${__function_name}" "installer" "DEBUG" "1215" "Digiops version to be installed is : ${digiops_download_version}"

digiops_existing_version=""
digiops_download_url=${__config_component_digiops_url}
log_it "${__function_name}" "installer" "DEBUG" "1220" "Digiops download site is: ${digiops_download_url}"
    
digiops_existing_path=$(which digiops)
if [[ $? -gt 0 ]]; then
	log_it "${__function_name}" "installer" "WARN" "1225" "Error while checking if digiops is already installed.  Ignoring and proceeding"
fi

if [[ -f ${digiops_existing_path} ]]; then
	log_it "${__function_name}" "installer" "INFO" "1230" "Digiops binary already available at path: ${digiops_existing_path}"
	digiops_existing_version=$(digiops version)
	if [[ "$digiops_existing_version" = "$digiops_download_version" ]]; then
		log_it "${__function_name}" "installer" "INFO" "1235" "Pre-existing digiops binary version is same as expected target version: ${digiops_download_version}. Using the pre-existing digiops binary."
	else
		log_it "${__function_name}" "installer" "WARN" "1240" "Pre-existing digiops binary version is: ${digiops_existing_version}.  Target version of digiops is: ${digiops_download_version}.  Backingup."
		sudo mv ${digiops_existing_path} ${digiops_existing_path}-${RANDOM}-bkp
	fi
fi
    
#digiops not available.  Download and install
digiops_binary="/tmp/${RANDOM}-digiops"
cp ${digi_dir}${digiops_download_url} ${digiops_binary}
if [[ $? -gt 0 ]]; then
	log_it "${__function_name}" "installer" "ERR" "1245" "Error while downloading digiops binary"
	exit 1
fi

if [[ -f ${digiops_binary} ]]; then
	log_it "${__function_name}" "installer" "DEBUG" "1250" "Downloaded digiops binary at: ${digiops_binary}"
		
	chmod +x ${digiops_binary}
	if [[ $? -gt 0 ]]; then
		log_it "${__function_name}" "installer" "ERR" "1255" "Error while changing the file perimissions for the downloaded digiops binary"
		exit 1
	else
		log_it "${__function_name}" "installer" "DEBUG" "1260" "Changed the access permission of digiops binary"
	fi

	digiops_download_version=$($digiops_binary version)
	log_it "${__function_name}" "installer" "DEBUG" "1265" "Downloaded digiops version is: $digiops_download_version"
	
	digiops_local_path=${__config_component_digiops_localPath}
	sudo mv ${digiops_binary} ${digiops_local_path}
	_exit_code=$?
	if [[ $? -gt 0 ]]; then
		log_it "${__function_name}" "installer" "ERR" "1270" "Error while moving digiops binary to ${digiops_local_path}"
		exit 1
	else        
		if [[ -f "${digiops_local_path}" ]]; then
			log_it "${__function_name}" "installer" "DEBUG" "1274" "Moved digiops binary to ${digiops_local_path}"
		else
			log_it "${__function_name}" "installer" "ERR" "1278" "Error while moving digiops binary to ${digiops_local_path}"
			exit 1
		fi
	fi

	#Check if digiops binary is in path
	digiops_new_path=$(which digiops)
	if [[ $? -gt 0 ]]; then
		log_it "${__function_name}" "installer" "ERR" "1280" "Error while checking if digiops binary is in path"
		exit 1
	fi

	if [[ "${digiops_new_path}" = "${digiops_local_path}" ]]; then
		log_it "${__function_name}" "installer" "DEBUG" "1282" "digiops binary is in path"
	else 
		log_it "${__function_name}" "installer" "ERR" "1284" "Different digiops binary is available in path."
		exit 1
	fi

	digiops_inpath_version=$(digiops version )
	if [[ "${digiops_inpath_version}" = "${digiops_download_version}" ]]; then
		log_it "${__function_name}" "installer" "DEBUG" "1286" "digiops binary in path has version: $digiops_download_version"
		log_it "${__function_name}" "installer" "INFO" "1288" "Successfully installed digiops version: $digiops_download_version"
	else
		log_it "${__function_name}" "installer" "ERR" "1290" "Incorrect version of digiops binary in path.  Expected version: ${digiops_download_version} Actual version: ${digiops_inpath_version}"
		exit 1
	fi
else
	log_it "${__function_name}" "installer" "ERR" "1292" "Not able to get handle on downloaded digiops binary"
	exit 1  
fi
